-- 코드를 입력하세요
SELECT REST_ID,REST_NAME,FOOD_TYPE,FAVORITES,ADDRESS,round(avg(REVIEW_SCORE),2) as SCORE 
from REST_INFO natural JOIN REST_REVIEW
WHERE ADDRESS LIKE "서울%"
GROUP BY REST_NAME
ORDER BY round(avg(REVIEW_SCORE),2) DESC, FAVORITES DESC;